### ISSUE TITLE
Something right

### ISSUE THREAD

**Issue by h9lk** [Fedora31/no-hats-bgum#1]
I spent quite lot of time in order to
> readme.md
> updates.txt
> credits.txt

Looked better and right, see edits on my fork

**Comment by Fedora31** [comment]
Hah! better and right indeed, they look much more consistent. I'd be more than happy to add them to the repo if you give me permission.

**Comment by h9lk** [comment]
> 
> 
> Hah! better and right indeed, they look much more consistent. I'd be more than happy to add them to the repo if you give me permission.

Glad that you liked my 3 hours of work on bringing files to "general view" and "standardization", made path easier by creating `pull request`. Everything was done - make it easier for you and others to navigate

**Comment by Fedora31** [comment]
Done; thanks for taking the time to do this, I really appreciate it.

**Comment by Fedora31** [comment]
Would you like a mention in the credits?

**Comment by h9lk** [comment]
if u want, sure, why not
