### ISSUE TITLE
Invisible Pyro head cosmetic

### ISSUE THREAD

**Issue by MistaMelon** [Fedora31/no-hats-bgum#9]
Hi I am not sure if I should post this here but I found another invisible pyro head while the "Nose candy" was equipped. https://wiki.teamfortress.com/wiki/Nose_Candy 
Love your work, can't play without it!

**Comment by Fedora31** [comment]
Hello! Yes, the nose candy is a hat that mysteriously doesn't work with the mod, and I don't know why. If you are using the "no_bugged_misc" VPK file, I made its first style invisible by default. As far as I know, there is sadly no fix for it. Please tell me if I misunderstood your comment.
Thanks for the support, always happy to see people enjoying the mod ;)

**Comment by MistaMelon** [comment]
Hi thanks for letting me know, I don't use the "no bugged misc" vpk file though. 
Maybe it was just a one time bug
